### ISSUE TITLE
[META 27] General Availability of ECS logging

### ISSUE THREAD

**Issue by russcam** [elastic/ecs-dotnet#119]
Relates: https://github.com/elastic/ecs-logging/issues/27

There is an effort to make ECS logging generally available across the language ecosystems of APM agents. As part of this, the ECS projects for .NET should be checked:

- [x] Validation against the spec
- [x] Integrate with APM by adding `trace.id` and `transaction.id` 
- [x] Review of dependency licenses
- [x] Documentation for the elastic.co website

**Comment by russcam** [comment]
All items are checked
