### ISSUE TITLE
GA meta ticket

### ISSUE THREAD

**Issue by codebrain** [elastic/ecs-dotnet#17]
**Tracking desires for GA release:**

- [x] Blog post for ECS .NET (to raise awareness + show usage) (in staging)
- [x] Update README.md in root repository as ".NET integrations repository" (look at sourcelink README for inspiration).
- [x] Determine how to handle pre-release package references - https://github.com/elastic/ecs-dotnet/pull/38
- [x] ~Decide how to publish/version the `Elastic.CommonSchemaNEST` assembly~ - not including in GA release
- [x] ~NLog Formatter~ - moving to an issue ticket and removing from this GA meta ticket
- [x] ~Reevaluate if we want to release prior versions as GA~ - opening as new ticket
- [x] Lock versioning to `MAJOR.MINOR.0` instead of `MAJOR.0.0` in the assembly identity - https://github.com/elastic/ecs-dotnet/pull/34
- [x] Lock versioning to `MAJOR.MINOR.0` instead of `MAJOR.0.0` in nuget package dependency ranges - https://github.com/elastic/ecs-dotnet/pull/38
