### ISSUE TITLE
[meta] Elasticsearch.Extensions.Logging GA

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/ecs-dotnet#95]
This ticket is a continuation of the following PR: https://github.com/elastic/ecs-dotnet/pull/85

- [x] Rely on Elasticsearch to generate the id
- [x] Move to a simple buffering approach and `_bulk`
- [x] Add a hook to be notified of failures
- [x] [`state` always an ` IEnumerable<KeyValuePair<string, object>>`](https://github.com/elastic/ecs-dotnet/pull/85#discussion_r441971235)?
- [x] Make sure `trace.id` flows into Elasticsearch so that Elastic APM can corrolate logs. (done https://github.com/elastic/ecs-dotnet/pull/96 )
- [x] Downgrade `Microsoft.Extensions.*` packages to `2.1.0`.
- [x] Should we default to `logstash-[current_date]` like the serilog sink does?
- [x] Remove `.Cast<char>` 
- [x] Remove unused `_w3CFormat` regular expression
- [x] `ExtractW3cSpanIdFromActivityId` has a possible detection edgecase that needs to be adressed. (https://github.com/elastic/ecs-dotnet/pull/96 eliminated it)
- [x] Introduce integration tests for this project.
- [x] Add support for `CloudConnectionPool` (https://github.com/elastic/ecs-dotnet/pull/98) ty @btastic !
- [x] [Make sure CreateConnectionPool throws instead of returning `null`](https://github.com/elastic/ecs-dotnet/pull/97#discussion_r457865292)

When all that is done we can:

- [x] Remove `<IsPackable>false</IsPackable>` from the project 

That should be enough to create and publish the package when we tag the next version.

cc @russcam @gregkalapos @sgryphon feel free to take an item and submit PR's. If it's a bigger chunk of work leave a note so we don't duplicate efforts.

**Comment by btastic** [comment]
Hello,

I just found this package while trying the elastic cloud trial. However, this logger does not seem to have the capability connect to the elastic cloud with its current API. Are there any plans to add that?

I'd like to contribute if you think this is a good addition.

Questions:
- As far as I can tell from the source code, you can add multiple Nodes to one configuration. That will make it not straight forward to define different ConnectionPoolTypes for each node. If the ConnectionPoolType is Cloud, you'd have to define it differently than other nodes as far as I understand. Or am I missing something?

**Comment by Mpdreamz** [comment]
Hey @btastic I think its a fantastic addition, looking forward to your PR 😄 

https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/connection-pooling.html#cloud-connection-pool

Ideally we find a way to abstract `ElasticsearchLoggerOptions` to an interface and have two implementations `ElasticsearchLoggerOptions` and `ElasticCloudLoggerOptions` where internally we only reference the interface. Otherwise `ElasticsearchLoggerOptions` turns into a big state machine.

It would be awesome if we could steer the user to a decision early e.g

```csharp
.ConfigureLogging((hostContext, loggingBuilder) => loggingBuilder.AddElasticsearch())
```
and
```csharp
.ConfigureLogging((hostContext, loggingBuilder) => loggingBuilder.AddElasticCloud(cloudId, username, pass))
.ConfigureLogging((hostContext, loggingBuilder) => loggingBuilder.AddElasticCloud(cloudId, apiKey))
```

**Comment by btastic** [comment]
Hey @Mpdreamz, thanks for the tips!

first I thought about doing it with an abstract class, but it turns out that the `OptionsMonitor<T>`  has a `class` constraint.

```
TypeLoadException: GenericArguments[0], 'Elasticsearch.Extensions.Logging.IElasticsearchLoggerOptions', on 'Microsoft.Extensions.Options.OptionsMonitor`1[TOptions]' violates the constraint of type parameter 'TOptions'.
```
See also the OptionsMonitor implementation here:
https://github.com/dotnet/runtime/blob/48e94eb47a5e1381434f007dc1024e0e2f806bae/src/libraries/Microsoft.Extensions.Options/src/OptionsMonitor.cs#L14

I think we need to approach this differently. But not sure how since I am not very fluent with the Options and configuration stuff.

**Comment by Mpdreamz** [comment]
Aye thinking out loud and in pseudocode (all names illustrative):

Wrap the endpoints in a custom class:

```
class ShipTo { 
    public ShipTo(IEnumerable<Uri> nodes, ConnectionPoolType poolType);
    public ShipTo(string cloudId);
    
    internal IConnectionPool CreateConnectionPool();

    public GetHashCode() {}
}
```

And set that instead of the current https://github.com/elastic/ecs-dotnet/blob/764253bc2364645cab331d367e46f296fc8bc43c/src/Elasticsearch.Extensions.Logging/ElasticsearchLoggerOptions.cs#L63

The custom `GetHashCode` on `ShipTo` will help fix an outstanding todo when options change to prevent the client to be recreated unnecessarily:

https://github.com/elastic/ecs-dotnet/blob/aa70621832bcd85b328c774a089fe40a678cab5c/src/Elasticsearch.Extensions.Logging/ElasticsearchDataShipper.cs#L109

**Comment by btastic** [comment]
Alright lets see.. https://github.com/elastic/ecs-dotnet/pull/98

**Comment by btastic** [comment]
Glad I was helpful! Is there any roadmap for expected GA release date? We're eager to use this in production :)

**Comment by sgryphon** [comment]
Hey guys, I was going to add some documentation for the Extensions package, and then the example didn't run on my machine.

Looking further, the Options pattern has been broken.  Options (and OptionsMonitor<>, etc) are supposed to be loading configuration settings, so need writeable properties, can't really have Funcs, etc (can't set a Func in JSON :-)

These is nothing wrong with having advanced options settable only from code only, but you still want to support direct settings via configuration.

The advantages of the standard configuration setting is that it automatically has support for a wide variety of scenarios, e.g. setting from appsettings.json, or for an Azure secrets vault only at run time (protect your apikey/password secrets), override with environment variables in a Docker container, or from command line parameters. It also supports automatic reload.

Yes, it means the Options is kind of a state machine, as your configuration in appsettings.json is basically just a text document that needs to parse and support all configuration options (then filter out invalid ones).

I'll see if I can clean up a bit.

**Comment by sgryphon** [comment]
For the question " Should we default to logstash-[current_date] like the serilog sink does? ", I don't think the question is correct. The question should be " Should we default to logstash-[current_date] like Logstash does? "

While there might be some tools that assume that logs use the same index as Logstash, I don't think it really makes logical sense as the default.  Logstash is not at all involved in the application, so why use it's name in the index?  That seems just weird.

And if a user does have a tool that is hard coded to look for logs generated by Logstash, then they can always change the configuration for their system (without inflicting it on every user).

**Comment by sgryphon** [comment]
" Remove unused _w3CFormat regular expression" is done, in `ElasticsearchLogger.cs` in commit e18b044.

**Comment by sgryphon** [comment]
@Mpdreamz can you also mark the Logstash format item as resolved. I checked the original comments and it was only a question to prompt if it was intentional, and that it didn't matter either way.   Nothing against logstash (which is part of the ELK stack), I just don't think we should masquerade as it by default. (And a user can configure it if they need to have that particular format, e.g. another tool that is hardcoded to look for logstash).

**Comment by sgryphon** [comment]
For State and IEnumerable<>, I added a reply to the original comment, copied here:

State could be anything, called from the public Log<TState>() method.  However usually it is not called directly, and either the high performance LoggerMessage.Define<>() is used, or one of the convenience extension methods, e.g. LogWarning().

The usual calls convert the passed in parameters to an internal state class, which is what you get access to in a logger provider. If you are just logging the message you can use the passed in formatter function.

However, for semantic logging you want to get out the individual parameter values, which I then put into the ECS labels dictionary. To do this we assume if the class implements IEnumerable<KeyValuePair<string,object>>, which the internal Microsoft class does, then we can use it to get the semantic labels and values.

There is a similar assumption made about BeginScope<TState>() to pull out additional semantic values. As we don't have access to the actual internal code, this is the best we can do and just handle it gracefully if the internals ever change. 

Nic Blumhardt blogged about it for Seq handling of Scope: https://nblumhardt.com/2016/11/ilogger-beginscope/

**Comment by sgryphon** [comment]
In short, state will currently always be IEnumerable<KeyValuePair<string,object>>, which is the internal implementation by Microsoft, if you use all the normal methods of logging.

If it isn't, then we degrade gracefully and ignore it. We can't extract semantic values (for labels), although we will still get the message from the formatter.

**Comment by nugroho-expereo** [comment]
Hi, Is there any updates on this issue?

We currently use Serilog and would love to replace it with this logging extension if this version is released.

**Comment by sgryphon** [comment]
@nugroho-expereo  The branches should all be ready to merge, just waiting on project admins to approve and do the merge (I don't have permission to).

**Comment by sgryphon** [comment]
@nugroho-expereo three of the branches are now merged; just one more and then ready to package and release, so should be soon.

**Comment by nugroho-expereo** [comment]
@sgryphon That's great. Thank you.

**Comment by russcam** [comment]
I'm looking to release this first as a 1.6.0-alpha1 on nuget in order to gather feedback before a GA release in 1.6.0.

**Comment by sgryphon** [comment]
@nugroho-expereo alpha release is up and available on nuget: https://www.nuget.org/packages/Elasticsearch.Extensions.Logging/1.6.0-alpha1

**Comment by nugroho-expereo** [comment]
Thank you. I will give it a try.

**Comment by AThomsen** [comment]
It's been half a year since the alpha. Any plans on a stable release or has this project been abandoned?

I'm asking because I'm trying to decide between using this directly or Serilog->ES sink

**Comment by sgryphon** [comment]
The ECS project overall has not really moved to 1.6 yet; it is still 1.5, hence why the logger provider is only an alpha. I think it has seen enough use (I use it fine) that it should be just 1.6 ... although I don't have permission to change that. 

I just use the prerelease.
